POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "leonardo@cat.com",
  "password": "num1cat"
}

#GET http://localhost:3000/auth/15

#GET http://localhost:3000/auth?email=leonardo@cat.com

#DELETE http://localhost:3000/auth/14
