POST http://localhost:3000/auth/signup
content-type: application/json

{
  "email": "user2@work.com",
  "password": "pass1256"
}

GET http://localhost:3000/auth/19

GET http://localhost:3000/auth?email=leonardo@cat.com

DELETE http://localhost:3000/auth/13

PATCH http://localhost:3000/auth/16
content-type: application/json

{ 
  "password": "thebest1"
}
