POST http://localhost:3000/auth/signin
content-type: application/json

{
  "email": "user7@work.com",
  "password": "pass4334"
}

GET http://localhost:3000/auth/19

GET http://localhost:3000/auth?email=leonardo@cat.com

DELETE http://localhost:3000/auth/13

PATCH http://localhost:3000/auth/16
content-type: application/json

{ 
  "password": "thebest1"
}
